In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
diabetes = pd.read_csv("diabetes.rwrite1.txt", encoding= "utf_8", delimiter=" ")
diabetes

age       sex       bmi       map        tc       ldl       hdl  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

          tch       ltg       glu    y  
0   -0.002592  0.019908 -0.017646  151  
1   -0.039493 -0.068330 -0.092204   75  
2   -0.002592  0.002864 -0.025930  141  
3    0.034309  0.022692 -0.009362  206  
4   -0.002592 -0.031991 -0.046641  135  
..        ...       ...       ...  ...  
437 -0.002592  0.031193  0.007207  178  
438  0.034309 -0.018118  0.044485  104  
439 -0.011080 -0.046879  0.015491  132  
440  0.026560  0.044528 -0.025930  220  
441 -0.039493 -0.004220  0.003064   57  

[442 rows x 11 columns]

In [ ]:
diabetes.info()

In [ ]:
diabetes.mean(), np.std(diabetes)

In [ ]:
sns.countplot(diabetes['age'])

In [ ]:
sns.countplot(diabetes['tc'])

In [ ]:
sns.countplot(diabetes['ldl'])

In [ ]:
sns.countplot(diabetes['hdl'])

In [ ]:
sns.countplot(diabetes['glu'])

In [ ]:
sns.set_theme(style="ticks")
sns.pairplot(diabetes, hue = "age")

In [ ]:
# Observando correlação entre as variáveis do dataframe

sns.set_theme(style="whitegrid")

corr_mat = diabetes.corr().stack().reset_index(name="correlation")

g = sns.relplot(
    data=corr_mat,
    x="level_0", y="level_1", hue="correlation", size="correlation",
    palette="vlag", hue_norm=(-1, 1), edgecolor=".7",
    height=10, sizes=(50, 250), size_norm=(-.2, .8),
)


g.set(xlabel="", ylabel="", aspect="equal")
g.despine(left=True, bottom=True)
g.ax.margins(.02)
for label in g.ax.get_xticklabels():
    label.set_rotation(90)
for artist in g.legend.legendHandles:
    artist.set_edgecolor(".7")

In [4]:
diabetes.shape

(442, 11)

In [12]:
# selecionamos as colunas de 1:4 porém a coluna 4 não entrará nessa variável.
X = diabetes.iloc[:, 0:10].values
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [13]:
y = diabetes.iloc[:, 10].values
y

array([151,  75, 141, 206, 135,  97, 138,  63, 110, 310, 101,  69, 179,
       185, 118, 171, 166, 144,  97, 168,  68,  49,  68, 245, 184, 202,
       137,  85, 131, 283, 129,  59, 341,  87,  65, 102, 265, 276, 252,
        90, 100,  55,  61,  92, 259,  53, 190, 142,  75, 142, 155, 225,
        59, 104, 182, 128,  52,  37, 170, 170,  61, 144,  52, 128,  71,
       163, 150,  97, 160, 178,  48, 270, 202, 111,  85,  42, 170, 200,
       252, 113, 143,  51,  52, 210,  65, 141,  55, 134,  42, 111,  98,
       164,  48,  96,  90, 162, 150, 279,  92,  83, 128, 102, 302, 198,
        95,  53, 134, 144, 232,  81, 104,  59, 246, 297, 258, 229, 275,
       281, 179, 200, 200, 173, 180,  84, 121, 161,  99, 109, 115, 268,
       274, 158, 107,  83, 103, 272,  85, 280, 336, 281, 118, 317, 235,
        60, 174, 259, 178, 128,  96, 126, 288,  88, 292,  71, 197, 186,
        25,  84,  96, 195,  53, 217, 172, 131, 214,  59,  70, 220, 268,
       152,  47,  74, 295, 101, 151, 127, 237, 225,  81, 151, 10

In [25]:
# Treinando os modelos

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
for i in range(30):
  kfold = KFold(n_splits = 10, shuffle = True, random_state = i)

  naive_bayes = GaussianNB()
  scores = cross_val_score(naive_bayes, X, y, cv = kfold)
  resultados_naive_bayes_cv.append(scores.mean())
  
  logistica = LogisticRegression()
  scores = cross_val_score(logistica, X, y, cv = kfold)
  resultados_logistica_cv.append(scores.mean())

  random_forest = RandomForestClassifier()
  scores = cross_val_score(random_forest, X, y, cv = kfold)
  resultados_forest_cv.append(scores.mean())

In [22]:
print(resultados_forest_cv)
print(resultados_logistica_cv)
print(resultados_naive_bayes_cv)

[0.004494949494949494, 0.0022727272727272726, 0.00909090909090909, 0.004545454545454545, 0.0022727272727272726, 0.006767676767676767, 0.011313131313131313, 0.004545454545454545, 0.004545454545454545, 0.004545454545454545, 0.00904040404040404, 0.004494949494949494, 0.004545454545454545, 0.006818181818181818, 0.004494949494949494, 0.006818181818181818, 0.008989898989898989, 0.004494949494949494, 0.006717171717171717, 0.006767676767676767, 0.006818181818181818, 0.00904040404040404, 0.0022727272727272726, 0.006818181818181818, 0.006818181818181818, 0.006818181818181818, 0.004494949494949494, 0.006767676767676767, 0.006767676767676768, 0.004545454545454545, 0.00909090909090909, 0.006818181818181818, 0.004545454545454545, 0.004545454545454545, 0.004494949494949494, 0.00904040404040404, 0.004545454545454545, 0.0022727272727272726, 0.006767676767676768, 0.006818181818181818, 0.011363636363636364, 0.006767676767676768, 0.013484848484848483, 0.004494949494949494, 0.004494949494949494, 0.00681818

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [41]:
diabetes.iloc[:, 10]

0      151
1       75
2      141
3      206
4      135
      ... 
437    178
438    104
439    132
440    220
441     57
Name: y, Length: 442, dtype: int64

In [37]:
naive_bayes.fit(X, y)
logistica.fit(X, y)
random_forest.fit(X, y)

RandomForestClassifier()

In [38]:
naive_bayes.predict(X)

array([263, 134, 138, 206, 214,  64,  71, 138, 110, 258, 101, 138, 134,
       138, 134, 171, 166, 196, 160, 134, 134,  71, 134, 245, 184, 124,
        59, 140, 134, 283, 134,  59, 341,  87, 134, 102, 134, 276, 217,
       116, 100, 134,  61, 103, 138, 110, 134, 134,  75, 138, 134, 138,
       128, 113, 134, 134, 128,  37, 103, 107,  61, 116,  39,  64,  71,
       163, 107, 107, 160, 134,  48, 270, 138, 196, 217, 107, 138, 134,
       152, 113, 143, 196, 134, 210,  48, 134, 116, 134,  71, 134,  98,
       164,  48,  48, 134, 162, 196, 279,  71, 214,  95, 102, 302, 196,
       134, 160, 134, 140, 232, 245,  71, 191, 246, 297, 258, 229, 196,
       258, 196, 134, 182, 173, 180,  84, 134, 161,  99, 109, 134, 173,
       274, 134, 107,  71, 134, 272,  59, 280, 336, 258, 107, 317, 235,
       134, 174, 134, 196, 128, 107, 126, 288, 134, 217, 110, 197, 186,
        25, 107,  64, 195, 134, 217, 140, 217, 134, 134,  70, 173, 268,
       152,  47, 134, 295,  70, 116, 134, 237, 258, 134, 214, 19

In [40]:
logistica.predict(X)

array([200,  72, 200, 200,  72,  72,  72,  72, 200, 200,  72, 200,  72,
       200,  72, 200, 200, 200, 200,  72,  72,  72,  72, 200, 200, 200,
        72, 200,  72,  72, 200,  72, 200,  72,  72,  72, 200,  72, 200,
        72, 200,  72, 200,  72, 200,  72,  72,  72,  72, 200,  72, 200,
        72, 200,  72,  72, 200,  72,  72,  72,  72, 200,  72,  72,  72,
       200, 200,  72,  72,  72,  72, 200,  72,  72, 200,  72, 200,  72,
        72,  72,  72,  72,  72,  72,  72,  72,  72,  72,  72,  72,  72,
       200, 200,  72,  72,  72, 200, 200,  72,  72,  72,  72, 200, 200,
       200,  72,  72, 200, 200, 200,  72,  72, 200, 200, 200, 200, 200,
       200, 200,  72, 200, 200, 200, 200,  72, 200,  72,  72,  72, 200,
       200,  72,  72,  72,  72, 200,  72, 200, 200, 200, 200, 200, 200,
        72, 200, 200, 200, 200, 200, 200, 200,  72, 200,  72,  72, 200,
        72,  72,  72, 200,  72, 200, 200, 200,  72,  72,  72, 200, 200,
       200,  72,  72, 200,  72, 200,  72, 200, 200,  72, 200, 20

In [42]:
random_forest.predict(X)

array([151,  75, 141, 206, 135,  97, 138,  63, 110, 310, 101,  69, 179,
       185, 118, 171, 166, 144,  97, 168,  68,  49,  68, 245, 184, 202,
       137,  85, 131, 283, 129,  59, 341,  87,  65, 102, 265, 276, 252,
        90, 100,  55,  61,  92, 259,  53, 190, 142,  75, 142, 155, 225,
        59, 104, 182, 128,  52,  37, 170, 170,  61, 144,  52, 128,  71,
       163, 150,  97, 160, 178,  48, 270, 202, 111,  85,  42, 170, 200,
       252, 113, 143,  51,  52, 210,  65, 141,  55, 134,  42, 111,  98,
       164,  48,  96,  90, 162, 150, 279,  92,  83, 128, 102, 302, 198,
        95,  53, 134, 144, 232,  81, 104,  59, 246, 297, 258, 229, 275,
       281, 179, 200, 200, 173, 180,  84, 121, 161,  99, 109, 115, 268,
       274, 158, 107,  83, 103, 272,  85, 280, 336, 281, 118, 317, 235,
        60, 174, 259, 178, 128,  96, 126, 288,  88, 292,  71, 197, 186,
        25,  84,  96, 195,  53, 217, 172, 131, 214,  59,  70, 220, 268,
       152,  47,  74, 295, 101, 151, 127, 237, 225,  81, 151, 10