### Medidas de Dirpersão

In [54]:
import pandas as pd
import numpy as np
import statistics
from scipy import stats
import math
import IPython.display as display
from PIL import Image

In [2]:
dados = np.arange(41)

In [3]:
dados

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [4]:
len(dados)

41

In [5]:
# média aritmetica simples

dados.sum() / len(dados)

20.0

In [6]:
dados.mean()

20.0

In [7]:
statistics.mean(dados)

20

In [8]:
# moda

statistics.mode(dados)

0

In [9]:
stats.mode(dados)

ModeResult(mode=array([0]), count=array([1]))

In [10]:
# mediana

dados_impar = [150, 144, 145, 156, 155]

In [11]:
(len(dados_impar) + 1 ) / 2

3.0

In [12]:
dados_impar[3 - 1]

145

In [13]:
dados_par = [155, 156, 157, 166, 168, 170]

In [14]:
(len(dados_par) / 2)

3.0

### Média Ponderada

In [15]:
notas = {'bimestre':['primeiro', 'segundo', 'terceiro', 'quarto'],
        'notas':[9, 8, 7, 3],
        'peso':[1, 2, 3, 4]}
notas

{'bimestre': ['primeiro', 'segundo', 'terceiro', 'quarto'],
 'notas': [9, 8, 7, 3],
 'peso': [1, 2, 3, 4]}

In [16]:
notas = pd.DataFrame(notas)
notas

bimestre  notas  peso
0  primeiro      9     1
1   segundo      8     2
2  terceiro      7     3
3    quarto      3     4

In [17]:
notas = np.array([9, 8, 7,3])
notas

array([9, 8, 7, 3])

In [18]:
pesos = np.array([1, 2, 3, 4])
pesos

array([1, 2, 3, 4])

In [19]:
(9*1 + 8*2 + 7*3 + 3*4) / (1+2+3+4)

5.8

In [20]:
media_ponderada = (notas * pesos).sum() / pesos.sum()
media_ponderada

5.8

In [21]:
np.average(notas, weights=pesos) # usamos o wigths como parametro, com os valores de pesos

5.8

### Média aritmética, Mode e Mediana

In [22]:
altura = [160, 155, 165, 167, 169, 171, 182, 155, 159, 167,
         164, 157, 177, 187, 199, 147, 167, 150, 149, 160,
         144, 155, 178, 199, 190, 156, 146, 178, 177, 158,
         177, 187, 157, 145, 167, 176, 167, 177, 155, 167]

In [23]:
altura = np.array([[160, 155, 165, 167, 169, 171, 182, 155, 159, 167,
         164, 157, 177, 187, 199, 147, 167, 150, 149, 160,
         144, 155, 178, 199, 190, 156, 146, 178, 177, 158,
         177, 187, 157, 145, 167, 176, 167, 177, 155, 167], [5, 6, 8, 1, 2, 3, 4, 6, 7, 8, 10, 182, 43, 43, 21,
                                                            12, 45, 3, 2, 4, 3, 6, 4, 3, 2, 5, 7, 1, 3, 6, 3, 6,
                                                            3, 6, 2, 4, 5, 6, 3, 2]])

In [24]:
altura = pd.DataFrame(altura)
altura

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0  160  155  165  167  169  171  182  155  159  167  ...  177  187  157  145   
1    5    6    8    1    2    3    4    6    7    8  ...    3    6    3    6   

    34   35   36   37   38   39  
0  167  176  167  177  155  167  
1    2    4    5    6    3    2  

[2 rows x 40 columns]

In [25]:
# Distribuição de Frequência

dicionario = {'inferior':[150, 154, 158, 162, 166, 170],
             'superior':[154, 158, 162, 166, 170, 174],
             'fi':[5, 9, 11, 7, 5, 3]}

In [26]:
import pandas as pd

In [27]:
dataset = pd.DataFrame(dicionario)
dataset

inferior  superior  fi
0       150       154   5
1       154       158   9
2       158       162  11
3       162       166   7
4       166       170   5
5       170       174   3

In [28]:
dataset['xi'] = (dataset['superior'] + dataset['inferior']) / 2
dataset

inferior  superior  fi     xi
0       150       154   5  152.0
1       154       158   9  156.0
2       158       162  11  160.0
3       162       166   7  164.0
4       166       170   5  168.0
5       170       174   3  172.0

In [29]:
dataset['fi.xi'] = (dataset['fi'] * dataset['xi'])
dataset

inferior  superior  fi     xi   fi.xi
0       150       154   5  152.0   760.0
1       154       158   9  156.0  1404.0
2       158       162  11  160.0  1760.0
3       162       166   7  164.0  1148.0
4       166       170   5  168.0   840.0
5       170       174   3  172.0   516.0

In [30]:
dataset['Fi'] = 0
dataset

inferior  superior  fi     xi   fi.xi  Fi
0       150       154   5  152.0   760.0   0
1       154       158   9  156.0  1404.0   0
2       158       162  11  160.0  1760.0   0
3       162       166   7  164.0  1148.0   0
4       166       170   5  168.0   840.0   0
5       170       174   3  172.0   516.0   0

In [31]:
freq_acumulada = [ ]
somatorio = 0
for linha in dataset.iterrows():
    # print(linha[1][2]) # realizado para fazer o somatório
    somatorio += linha[1][2]
    freq_acumulada.append(somatorio)

In [32]:
freq_acumulada

[5.0, 14.0, 25.0, 32.0, 37.0, 40.0]

In [33]:
dataset['Fi'] = freq_acumulada
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [34]:
dataset['fi'].sum(), dataset['fi.xi'].sum()

(40, 6428.0)

In [35]:
media = (dataset['fi.xi'].sum() / dataset['fi'].sum())
media

160.7

In [36]:
### Moda

dataset['fi'].max()

11

In [37]:
dataset[dataset['fi'] == dataset['fi'].max()]

inferior  superior  fi     xi   fi.xi    Fi
2       158       162  11  160.0  1760.0  25.0

In [38]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi']

2    160.0
Name: xi, dtype: float64

In [39]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values

array([160.])

In [40]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

160.0

In [41]:
# Mediana

dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [42]:
fi_2 = dataset['fi'].sum() / 2
fi_2

20.0

### Média geométrica, média harmônica e média quadrática

In [43]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [44]:
from scipy.stats.mstats import gmean

In [48]:
dados = [160, 155, 165, 167, 169, 171, 182, 155, 159, 167,
         164, 157, 177, 187, 199, 147, 167, 150, 149, 160,
         144, 155, 178, 199, 190, 156, 146, 178, 177, 158,
         177, 187, 157, 145, 167, 176, 167, 177, 155, 167]

In [49]:
gmean(dados)

165.9891936835495

In [50]:
from scipy.stats.mstats import hmean

In [51]:
hmean(dados)

165.4148478666247

In [52]:
def quadraticmean(dados):
    return math.sqrt(sum(n * n for n in dados) / len(dados))

In [53]:
quadraticmean(dados)

167.1710949895346

# Quartis

In [ ]:
display.display(Image.open('./recursos/quartis.png'))