### Medidas de Dirpersão

In [10]:
import pandas as pd
import numpy as np
import statistics
from scipy import stats
import math

In [11]:
dados = np.arange(41)

In [12]:
dados

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [15]:
len(dados)

41

In [14]:
# média aritmetica simples

dados.sum() / len(dados)

20.0

In [16]:
dados.mean()

20.0

In [17]:
statistics.mean(dados)

20

In [18]:
# moda

statistics.mode(dados)

0

In [19]:
stats.mode(dados)

ModeResult(mode=array([0]), count=array([1]))

In [20]:
# mediana

dados_impar = [150, 144, 145, 156, 155]

In [21]:
(len(dados_impar) + 1 ) / 2

3.0

In [23]:
dados_impar[3 - 1]

145

In [24]:
dados_par = [155, 156, 157, 166, 168, 170]

In [25]:
(len(dados_par) / 2)

3.0

### Média Ponderada

In [30]:
notas = {'bimestre':['primeiro', 'segundo', 'terceiro', 'quarto'],
        'notas':[9, 8, 7, 3],
        'peso':[1, 2, 3, 4]}
notas

{'bimestre': ['primeiro', 'segundo', 'terceiro', 'quarto'],
 'notas': [9, 8, 7, 3],
 'peso': [1, 2, 3, 4]}

In [32]:
notas = pd.DataFrame(notas)
notas

bimestre  notas  peso
0  primeiro      9     1
1   segundo      8     2
2  terceiro      7     3
3    quarto      3     4

In [34]:
notas = np.array([9, 8, 7,3])
notas

array([9, 8, 7, 3])

In [36]:
pesos = np.array([1, 2, 3, 4])
pesos

array([1, 2, 3, 4])

In [37]:
(9*1 + 8*2 + 7*3 + 3*4) / (1+2+3+4)

5.8