## Estudo Numpy

In [1]:
import numpy as np

In [2]:
# Apresentam objetos N-dimensional

data = np.random.randn(2 ,3)
data

array([[-0.08566209,  0.14988779, -0.24516713],
       [ 0.13896759, -0.07876518, -0.33386521]])

In [3]:
data * 10 # todos os elementos são multiplicados por 10

array([[-0.85662094,  1.49887789, -2.45167131],
       [ 1.38967585, -0.78765177, -3.33865213]])

In [4]:
data + data # neste segundo exemplo, os elementos correspondentes são somados

array([[-0.17132419,  0.29977558, -0.49033426],
       [ 0.27793517, -0.15753035, -0.66773043]])

# O que são ndarrays? 

- Ndarrays são contêiners genéricos multidimensionais para dados homogêneos; 
- Isso significa que todos os elementos devem ser do mesmo tipo.

In [6]:
# podemos verificar o shape do array

data.shape # uma tupla que indica o tamanho de cada dimensão 
# 2 linhas 3 colunas

(2, 3)

In [7]:
# podemos verificar o tipo do dado

data.dtype # um objeto que informa o tipo do dado

dtype('float64')

#### Criando ndarrys

In [9]:
# podemos converter uma lista em um array, com a função array()

dia = [2, 5, 10, 15, 31]

arr1 = np.array(dia)
arr1

# array([ 2,  5, 10, 15, 31])

array([ 2,  5, 10, 15, 31])

In [11]:
# uma lista de lista será convertida em um array multidimensional

semana = [['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo'], [1, 2, 3, 4, 5, 6, 7]]

arr2 = np.array(semana)
arr2

array([['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado',
        'domingo'],
       ['1', '2', '3', '4', '5', '6', '7']], dtype='<U11')

In [13]:
arr2.dtype
arr2.shape

(2, 7)

In [18]:
dias = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] # lista de listas
dias = np.array(dias) # convertendo a lista em array
dias # array (multidimensional, 3 linhas com 4 colunas)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
dias.shape

(3, 4)

In [21]:
dias.dtype

dtype('int32')

In [22]:
# Podemos criar arrays com valores embutidos

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.empty((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [27]:
# Função arange()

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Tipos de Dados para ndarray

In [30]:
arr = np.array([1, 2, 3], dtype=np.float64)
arr

array([1., 2., 3.])

In [32]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3])

In [39]:
# fazendo cast com array

arr = np.array([2, 6, 8], dtype=np.int32)

float_arr = arr.astype(np.float64)
float_arr

array([2., 6., 8.])

In [36]:
arr.dtype

dtype('int32')

In [38]:
float_arr.dtype

dtype('float64')

In [43]:
# podemos converter uma string que representem números para o formato numérico

numeric_string = np.array(['12', '26', '32', '64'])
numeric_string.astype(int)
numeric_string

array(['12', '26', '32', '64'], dtype='<U2')

In [44]:
# ouuu
arr_numeric = np.array(numeric_string, dtype=np.string_)
arr_numeric

array([b'12', b'26', b'32', b'64'], dtype='|S2')

### Aritmética com arrays Numpy
#### Permitem expressar operações em lote nos dados; Qualquer operação aritmética entre arrays de mesmo tamanho faz a operação ser aplicada em todos os elementos

In [45]:
arr3 = np.array([[1., 2., 3.,], [4., 5., 6.]])

In [46]:
arr3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr3 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [48]:
arr3 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [49]:
arr3 + arr3

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [50]:
arr3 - arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
arr3 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [52]:
arr3 > 4.5

array([[False, False, False],
       [False,  True,  True]])

In [53]:
arr3 < 1.0

array([[False, False, False],
       [False, False, False]])

##### Ao utilizarmos os operadores no array. A operação é aplicada a todos os elementos do array. Possibilitando as operações em lotes, sem a necessidade do uso do for

### Indexação básica e fatiamento

In [1]:
import numpy as np

In [3]:
### se comportam semelhantes a lista no Python

arr_fat = np.arange(10)
arr_fat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr_fat[5] # retorna 5
arr_fat[8] # retorna 8

8

In [7]:
arr_fat[3:8]

array([3, 4, 5, 6, 7])

In [8]:
arr_fat[5] = 12
arr_fat

array([ 0,  1,  2,  3,  4, 12,  6,  7,  8,  9])

In [11]:
arr_fat[6:9] = 3.5
# valor sofrendo broadcast dentro desse 'fatiamento' do array
arr_fat

array([ 0,  1,  2,  3,  4, 12,  3,  3,  3,  9])

#### Uma observação importante é a diferença entre os arrays das listas do Python. Os arrays não são copiados, e qualquer modificação na visualização se refletirá no array original

In [13]:
arr_slice = arr_fat[6:9] # array([3, 3, 3])
arr_slice

array([3, 3, 3])

In [14]:
arr_slice[1] = 1245
# Portanto qualquer modificação se reflete no array_fat (original)
arr_fat

array([   0,    1,    2,    3,    4,   12,    3, 1245,    3,    9])

In [18]:
# Para podermos copiar uma fatia (ou um array) precisamos copiar explicitamente tal array

arr_fat[1:5].copy()

array([1, 2, 3, 4])

In [27]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2_1d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

In [21]:
arr2d[2]

array([7, 8, 9])

In [25]:
# Muito parecido com listas, os arrays podem ter seus valores acessados individualmente

arr2d[1][2] # out : 6
arr2d[0][1] # out: 2

# Ou podemos passar uma lista com os indices separados por vírgula

arr2d[0,2] # out : 3

3

In [29]:
arr3d = arr2_1d.copy()
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2d[:2]

# Seleciona um intervalo de elementos ao longo de um eixo.

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2d[:2, 1:] # seleciona apenas as duas primeiras linhas a partir da coluna de indice 1

array([[2, 3],
       [5, 6]])

In [34]:
# selecione apenas a segunda linha (a de indice 1 ) porém as duas primeiras colunas (0:1)
arr2d[1, :2]

array([4, 5])

In [39]:
# Semelhantemente, podemos selecionar a terceira coluna (indice 2), mas somente as duas primeiras linhas
arr2d[:2, 2]

array([3, 6])

In [40]:
arr2d[:, :1] # tras os valores da primeira coluna

array([[1],
       [4],
       [7]])

In [43]:
arr2d[:1, :] # trás todos os valores da primeira linha

array([[1, 2, 3]])

In [46]:
arr2d[:, 2:] # trás apenas os valores da coluna 2 
arr2d[:, :2] # trás os valores das colunas 1 e 2 

array([[1, 2],
       [4, 5],
       [7, 8]])

### Indexação Booleana


In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4) # 7 linhas e 4 colunas

In [49]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [50]:
data

array([[ 0.12319057, -1.50213318,  0.21633819, -0.9485682 ],
       [ 0.62956807, -0.26698149, -1.0518198 , -1.10240481],
       [-1.42474947, -0.18850548,  0.52652836,  1.17844602],
       [-2.03210512, -0.20047752,  0.67703945,  0.58257202],
       [ 0.96996072,  0.84727555,  1.98626874, -2.23268551],
       [-0.85594043,  0.55887996, -1.48693078, -1.35776219],
       [-0.5604703 ,  0.38839671,  1.67195051, -0.34168856]])

In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [60]:
data[names == 'Bob', 3]

TypeError: list indices must be integers or slices, not tuple

In [61]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [62]:
data[~(names == 'Bob')]

TypeError: only integer scalar arrays can be converted to a scalar index

In [63]:
cond = names == 'Bob'

In [64]:
data[~cond]

TypeError: only integer scalar arrays can be converted to a scalar index

In [66]:
mask = (names == 'Bob') | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [67]:
data[mask]

TypeError: only integer scalar arrays can be converted to a scalar index

In [69]:
data[data < 0] = 0

TypeError: '<' not supported between instances of 'list' and 'int'

### Indexação Sofisticada