## Estudo Numpy

In [1]:
import numpy as np

In [2]:
# Apresentam objetos N-dimensional

data = np.random.randn(2 ,3)
data

array([[-0.08566209,  0.14988779, -0.24516713],
       [ 0.13896759, -0.07876518, -0.33386521]])

In [3]:
data * 10 # todos os elementos são multiplicados por 10

array([[-0.85662094,  1.49887789, -2.45167131],
       [ 1.38967585, -0.78765177, -3.33865213]])

In [4]:
data + data # neste segundo exemplo, os elementos correspondentes são somados

array([[-0.17132419,  0.29977558, -0.49033426],
       [ 0.27793517, -0.15753035, -0.66773043]])

# O que são ndarrays? 

#### Ndarrays são contêiners genéricos multidimensionais para dados homogêneos; 

#### Isso significa que todos os elementos devem ser do mesmo tipo.

In [6]:
# podemos verificar o shape do array

data.shape # uma tupla que indica o tamanho de cada dimensão 
# 2 linhas 3 colunas

(2, 3)

In [7]:
# podemos verificar o tipo do dado

data.dtype # um objeto que informa o tipo do dado

dtype('float64')

#### Criando ndarrys

In [9]:
# podemos converter uma lista em um array, com a função array()

dia = [2, 5, 10, 15, 31]

arr1 = np.array(dia)
arr1

# array([ 2,  5, 10, 15, 31])

array([ 2,  5, 10, 15, 31])

In [11]:
# uma lista de lista será convertida em um array multidimensional

semana = [['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo'], [1, 2, 3, 4, 5, 6, 7]]

arr2 = np.array(semana)
arr2

array([['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado',
        'domingo'],
       ['1', '2', '3', '4', '5', '6', '7']], dtype='<U11')

In [13]:
arr2.dtype
arr2.shape

(2, 7)

In [18]:
dias = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] # lista de listas
dias = np.array(dias) # convertendo a lista em array
dias # array (multidimensional, 3 linhas com 4 colunas)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
dias.shape

(3, 4)

In [21]:
dias.dtype

dtype('int32')

In [22]:
# Podemos criar arrays com valores embutidos

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.empty((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [27]:
# Função arange()

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Tipos de Dados para ndarray

In [30]:
arr = np.array([1, 2, 3], dtype=np.float64)
arr

array([1., 2., 3.])

In [32]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3])

In [39]:
# fazendo cast com array

arr = np.array([2, 6, 8], dtype=np.int32)

float_arr = arr.astype(np.float64)
float_arr

array([2., 6., 8.])

In [36]:
arr.dtype

dtype('int32')

In [38]:
float_arr.dtype

dtype('float64')

In [43]:
# podemos converter uma string que representem números para o formato numérico

numeric_string = np.array(['12', '26', '32', '64'])
numeric_string.astype(int)
numeric_string

array(['12', '26', '32', '64'], dtype='<U2')

In [44]:
# ouuu
arr_numeric = np.array(numeric_string, dtype=np.string_)
arr_numeric

array([b'12', b'26', b'32', b'64'], dtype='|S2')

### Aritmética com arrays Numpy
#### Permitem expressar operações em lote nos dados; Qualquer operação aritmética entre arrays de mesmo tamanho faz a operação ser aplicada em todos os elementos

In [45]:
arr3 = np.array([[1., 2., 3.,], [4., 5., 6.]])

In [46]:
arr3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr3 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [48]:
arr3 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [49]:
arr3 + arr3

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [50]:
arr3 - arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
arr3 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [52]:
arr3 > 4.5

array([[False, False, False],
       [False,  True,  True]])

In [53]:
arr3 < 1.0

array([[False, False, False],
       [False, False, False]])

##### Ao utilizarmos os operadores no array. A operação é aplicada a todos os elementos do array. Possibilitando as operações em lotes, sem a necessidade do uso do for