In [1]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(arr[5])
print(arr[2])
print(arr[0])
print(arr[5:6])
print(arr[5:7])
print(arr[5:8])
print(arr[5:9])

5
2
0
[1 2 3 4 5 6 7]
[5]
[5 6]
[5 6 7]
[5 6 7 8]
