In [1]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(arr[5])
print(arr[2])
print(arr[0])
print(arr[5:6])
print(arr[5:7])
print(arr[5:8])
print(arr[5:9])

5
2
0
[1 2 3 4 5 6 7]
[5]
[5 6]
[5 6 7]
[5 6 7 8]


In [16]:
arr[5:8] = 12

In [17]:
arr # array sofrendo broadcasting

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

##### Portanto uma distinção entre arrays e listas é que se você atribuir um valor a um pedaço do array, ele será propagado por naquela fatia selecionada. Alterando assim o valor original (que não é salvo) do array

In [21]:
# Podemos acessar elementos individualmente de um array

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# o eixo 0 são as linhas 
# Já o eixo 1 são as colunas
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2[2] #acessando o valor de indice 2 do array

array([7, 8, 9])

In [25]:
# acessando os valores individuais do array
arr2[2][0] # 7
arr2[2][1] # 8
arr2[2][2] # 9

9

### Indexação em fatias