## Estudo Numpy

In [1]:
import numpy as np

In [3]:
# Apresentam objetos N-dimensional

data = np.random.randn(2 ,3)
data

array([[ 0.02322444, -0.16303063, -1.10853278],
       [ 0.43154724,  0.97041416, -0.972724  ]])

In [4]:
data * 10 # todos os elementos são multiplicados por 10

array([[  0.23224441,  -1.63030627, -11.0853278 ],
       [  4.31547244,   9.70414161,  -9.72723997]])

In [5]:
data + data # neste segundo exemplo, os elementos correspondentes são somados

array([[ 0.04644888, -0.32606125, -2.21706556],
       [ 0.86309449,  1.94082832, -1.94544799]])

# O que são ndarrays? 

### Ndarrays são contêiners genéricos multidimensionais para dados homogêneos; 

### Isso significa que todos os elementos devem ser do mesmo tipo.

In [6]:
# podemos verificar o shape do array

data.shape # uma tupla que indica o tamanho de cada dimensão 
# 2 linhas 3 colunas

(2, 3)

In [7]:
# podemos verificar o tipo do dado

data.dtype # um objeto que informa o tipo do dado

dtype('float64')