## Estudo Numpy

In [1]:
import numpy as np

In [3]:
# Apresentam objetos N-dimensional

data = np.random.randn(2 ,3)
data

array([[ 0.02322444, -0.16303063, -1.10853278],
       [ 0.43154724,  0.97041416, -0.972724  ]])

In [4]:
data * 10 # todos os elementos são multiplicados por 10

array([[  0.23224441,  -1.63030627, -11.0853278 ],
       [  4.31547244,   9.70414161,  -9.72723997]])

In [5]:
data + data # neste segundo exemplo, os elementos correspondentes são somados

array([[ 0.04644888, -0.32606125, -2.21706556],
       [ 0.86309449,  1.94082832, -1.94544799]])

# O que são ndarrays? 

#### Ndarrays são contêiners genéricos multidimensionais para dados homogêneos; 

#### Isso significa que todos os elementos devem ser do mesmo tipo.

In [6]:
# podemos verificar o shape do array

data.shape # uma tupla que indica o tamanho de cada dimensão 
# 2 linhas 3 colunas

(2, 3)

In [7]:
# podemos verificar o tipo do dado

data.dtype # um objeto que informa o tipo do dado

dtype('float64')

#### Criando ndarrys

In [9]:
# podemos converter uma lista em um array, com a função array()

dia = [2, 5, 10, 15, 31]

arr1 = np.array(dia)
arr1

# array([ 2,  5, 10, 15, 31])

array([ 2,  5, 10, 15, 31])

In [11]:
# uma lista de lista será convertida em um array multidimensional

semana = [['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo'], [1, 2, 3, 4, 5, 6, 7]]

arr2 = np.array(semana)
arr2

array([['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado',
        'domingo'],
       ['1', '2', '3', '4', '5', '6', '7']], dtype='<U11')

In [13]:
arr2.dtype
arr2.shape

(2, 7)

In [18]:
dias = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] # lista de listas
dias = np.array(dias) # convertendo a lista em array
dias # array (multidimensional, 3 linhas com 4 colunas)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
dias.shape

(3, 4)

In [21]:
dias.dtype

dtype('int32')

In [22]:
# Podemos criar arrays com valores embutidos

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.empty((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])