In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
ds = pd.read_csv('./Bases de dados/census.csv')
display(ds.head())

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [4]:
ds.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  
32556             0             0             38   United-States   <=50K  
32557             0             0             40   United-States    >50K  
32558             0             0             40   United-States   <=50K  
32559             0             0             20   United-States   <=50K  
32560         15024             0             40   United-States    >50K

### Amostragem aleatória

In [5]:
df_aleatoria_simples = ds.sample(n = 100, random_state=1)
#random-state sempre vai retornar o mesmo resultado. Idependente do número de vezes
# sempre teremos a mesma amostra
# excelente para replicar o ds

In [6]:
df_aleatoria_simples.shape

(100, 15)

In [7]:
df_aleatoria_simples.head()

age          workclass  final-weight   education  education-num  \
9646    62   Self-emp-not-inc         26911     7th-8th              4   
709     18            Private        208103        11th              7   
7385    25            Private        102476   Bachelors             13   
16671   33            Private        511517     HS-grad              9   
21932   36            Private        292570        11th              7   

            marital-status          occupation     relationship    race  \
9646               Widowed       Other-service    Not-in-family   White   
709          Never-married       Other-service   Other-relative   White   
7385         Never-married     Farming-fishing        Own-child   White   
16671   Married-civ-spouse      Prof-specialty          Husband   White   
21932        Never-married   Machine-op-inspct        Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
9646    Female             0             0             66   United-States   
709       Male             0             0             25   United-States   
7385      Male         27828             0             50   United-States   
16671     Male             0             0             40   United-States   
21932   Female             0             0             40   United-States   

       income  
9646    <=50K  
709     <=50K  
7385     >50K  
16671   <=50K  
21932   <=50K

In [8]:
def amostragemSimples(ds, amostras):
    return ds.sample(n = amostras, random_state=1)

In [9]:
df_aleatoria_simples = amostragemSimples(ds, 100)
df_aleatoria_simples.shape

(100, 15)

In [10]:
df_aleatoria_simples.head()

age          workclass  final-weight   education  education-num  \
9646    62   Self-emp-not-inc         26911     7th-8th              4   
709     18            Private        208103        11th              7   
7385    25            Private        102476   Bachelors             13   
16671   33            Private        511517     HS-grad              9   
21932   36            Private        292570        11th              7   

            marital-status          occupation     relationship    race  \
9646               Widowed       Other-service    Not-in-family   White   
709          Never-married       Other-service   Other-relative   White   
7385         Never-married     Farming-fishing        Own-child   White   
16671   Married-civ-spouse      Prof-specialty          Husband   White   
21932        Never-married   Machine-op-inspct        Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
9646    Female             0             0             66   United-States   
709       Male             0             0             25   United-States   
7385      Male         27828             0             50   United-States   
16671     Male             0             0             40   United-States   
21932   Female             0             0             40   United-States   

       income  
9646    <=50K  
709     <=50K  
7385     >50K  
16671   <=50K  
21932   <=50K

### Amostragem Sistemática

população / amostra


In [12]:
len(ds) // 100

325

In [20]:
# sorteando um numero entre 0 e 325
random.seed(1)
random.randint(0, 325)

68

In [23]:
# para selecionar sistematicamente uma amostra de 325 em 325 até o final do dataset
np.arange(68, len(ds), step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [32]:
def amostragemSistematica(ds, amostras):
    intervalo = len(ds) // amostras 
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inicio, len(ds), step=intervalo)
    amostra_sistematica = ds.iloc[indices]
    return amostragemSistematica

In [39]:
df_amostragem_sistematica = amostragemSistematica(ds, 100)
df_amostragem_sistematica.shape

AttributeError: 'function' object has no attribute 'shape'

In [38]:
df_amostragem_sistematica.head()

AttributeError: 'function' object has no attribute 'head'

### Amostragem em Grupo

In [ ]:
## definimos os grupos como identificadores

In [40]:
len(ds) / 10 # gerando 10 grupos, teremos 3256 pessoas por grupo

3256.1

In [43]:
grupos = []
id_grupo = 0
contagem = 0 
for _ in ds.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

In [45]:
# verificando se fizemos a divisão corretamente
# trás os valores únicos de cada grupo
# e a quantidade existente em cada grupo
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [47]:
np.shape(grupos), ds.shape

((32561,), (32561, 15))

In [48]:
# adicionando a coluna grupo ao dataset

ds['grupo'] = grupos

In [49]:
ds.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [50]:
ds.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  \
32556             0             0             38   United-States   <=50K   
32557             0             0             40   United-States    >50K   
32558             0             0             40   United-States   <=50K   
32559             0             0             20   United-States   <=50K   
32560         15024             0             40   United-States    >50K   

       grupo  
32556      9  
32557      9  
32558      9  
32559      9  
32560      9

In [61]:
#random.seed(1)
random.randint(0, 9)

7

In [63]:
# filtramos o grupo que queremos do dataset
df_agrupamento = ds[ds['grupo'] == 7]
df_agrupamento.shape

(3257, 16)

In [64]:
# contamos a quantidade de registros existentes no grupo 7
df_agrupamento['grupo'].value_counts()

7    3257
Name: grupo, dtype: int64